# -*- coding: utf-8 -*-
"""day14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fl33uaYWnlTv-khq5tUZa3ijSjDI1LTw
"""

import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=sns.load_dataset('titanic')
df

df.head(8)

df.tail(10)

df.sample()

df.info()

df.sample(11)

df.duplicated()

df.duplicated().sum()

df[df.duplicated()]

df.drop_duplicates(inplace=True)

df.reset_index(drop=True)

df.isnull().sum()

df.dropna()

sns.heatmap(df.isnull())
plt.show()

df.drop('fare',axis=1)

df.dtypes

df['embark_town']

df['embark_town'].mode()[0]

df['embark_town'].isnull().sum()

df['embark_town'].fillna('Southampton')

df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

df['fare'].median()

df['embarked'].isnull().sum()

df['embarked'].fillna(df['embark_town'].mode()[0],inplace=True)

df.describe()

df.describe(include='object')

df['embarked']

